<a href="https://colab.research.google.com/github/Kartik2002-KatiL/kartik-raj-/blob/kartik/kartik_pw_module_6_ass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns using array transpose
interchanged_array = array.transpose()

print("Original array:")
print(array)
print("\nArray with interchanged rows and columns:")
print(interchanged_array)


Original array:
[[ 7 47  9]
 [54 25 96]
 [71 93 90]]

Array with interchanged rows and columns:
[[ 7 54 71]
 [47 25 93]
 [ 9 96 90]]


In [2]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped into a 2x5 array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped into a 5x2 array:")
print(array_5x2)



Reshaped into a 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into a 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Create a 4x4 NumPy array with random float values
array = np.random.rand(4, 4)

# Create a 6x6 array filled with zeros
bordered_array = np.zeros((6, 6))

# Copy the original array into the center of the bordered array
bordered_array[1:5, 1:5] = array

print("Original array:")
print(array)
print("\nArray with a border of zeros:")
print(bordered_array)


Original array:
[[0.92666392 0.40882521 0.40365183 0.49715408]
 [0.48728168 0.92487851 0.45880013 0.74391788]
 [0.05333073 0.71039026 0.79624906 0.83529064]
 [0.11568412 0.0219548  0.63757822 0.1749117 ]]

Array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.92666392 0.40882521 0.40365183 0.49715408 0.        ]
 [0.         0.48728168 0.92487851 0.45880013 0.74391788 0.        ]
 [0.         0.05333073 0.71039026 0.79624906 0.83529064 0.        ]
 [0.         0.11568412 0.0219548  0.63757822 0.1749117  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print(array)


[10 15 20 25 30 35 40 45 50 55 60]


In [5]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Uppercase transformation
uppercase_array = np.char.upper(array)
print("Uppercase array:", uppercase_array)

# Lowercase transformation
lowercase_array = np.char.lower(array)
print("Lowercase array:", lowercase_array)

# Title case transformation
titlecase_array = np.char.title(array)
print("Titlecase array:", titlecase_array)

# Swapcase transformation
swapcase_array = np.char.swapcase(array)
print("Swapcase array:", swapcase_array)


Uppercase array: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase array: ['python' 'numpy' 'pandas']
Titlecase array: ['Python' 'Numpy' 'Pandas']
Swapcase array: ['PYTHON' 'NUMPY' 'PANDAS']


In [6]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

# Generate a NumPy array of words
words_array = np.array(['hello', 'world', 'python'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

print("Original array:", words_array)
print("Array with spaces between characters:", spaced_words_array)


Original array: ['hello' 'world' 'python']
Array with spaces between characters: ['h e l l o' 'w o r l d' 'p y t h o n']


In [7]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

# Create two 2D NumPy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
addition_result = np.add(array1, array2)
print("Element-wise addition:")
print(addition_result)

# Element-wise subtraction
subtraction_result = np.subtract(array1, array2)
print("\nElement-wise subtraction:")
print(subtraction_result)

# Element-wise multiplication
multiplication_result = np.multiply(array1, array2)
print("\nElement-wise multiplication:")
print(multiplication_result)

# Element-wise division
division_result = np.divide(array1, array2)
print("\nElement-wise division:")
print(division_result)


Element-wise addition:
[[ 6  8]
 [10 12]]

Element-wise subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Element-wise division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [8]:
# prompt: 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

print("Identity matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal elements:")
print(diagonal_elements)


Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements:
[1. 1. 1. 1. 1.]


In [9]:
# prompt: 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

def is_prime(n):
  """Checks if a number is prime."""
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

# Generate a NumPy array of 100 random integers between 0 and 1000
array = np.random.randint(0, 1001, size=100)

# Find and display all prime numbers in the array
prime_numbers = [num for num in array if is_prime(num)]

print("Original array:", array)
print("Prime numbers in the array:", prime_numbers)


Original array: [ 49 934 531 206 175 142 752 343 436 451 221  84 980 856 578 127  64 966
 232 604 646 603 300 731 234 733 880 412  38 342 345 560 416 697 446  99
 915 644 124 568 183 247 839 792  71 658  36 259 567 401 957 926 440 290
 504 260 349 140 408 238 139  83 413 381 153 225 661 777 478 693 773 365
 117 660 783 920 362 936 165 603 862 717 103 783 849 962 100 643 704 931
 870 967 671  91 755 797 908 686  88 708]
Prime numbers in the array: [127, 733, 839, 71, 401, 349, 139, 83, 661, 773, 103, 643, 967, 797]


In [10]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
temperatures = np.random.randint(15, 35, size=30)

# Calculate weekly averages
weekly_averages = []
for i in range(0, len(temperatures), 7):
  week_temperatures = temperatures[i:i+7]
  if len(week_temperatures) > 0:
    weekly_average = np.mean(week_temperatures)
    weekly_averages.append(weekly_average)


print("Daily temperatures:", temperatures)
print("Weekly averages:", weekly_averages)


Daily temperatures: [21 27 24 28 26 16 25 33 18 33 20 26 15 25 23 30 27 30 18 34 33 18 34 30
 22 25 25 17 19 22]
Weekly averages: [23.857142857142858, 24.285714285714285, 27.857142857142858, 24.428571428571427, 20.5]
